if("undefined"===typeof window.AddShoppersTriggerRunner)window.AddShoppersTriggerRunner=function(){var C,u,D,x,q,L,y,r,z,A,m,E;function M(a){var b=typeof a;return null!=a&&("object"==b||"function"==b)}function X(a,b,c){function d(b){var c=o,d=v;o=v=void 0;f=b;return n=a.apply(d,c)}function j(a){var c=a-p,a=a-f;return void 0===p||c>=b||0>c||h&&a>=g}function e(){var a=Date.now();if(j(a))return N(a);var c=setTimeout,d=e,n;n=a-f;a=b-(a-p);n=h?Math.min(a,g-n):a;l=c(d,n)}function N(a){l=void 0;if(k&&o)return d(a);
o=v=void 0;return n}function i(){var a=Date.now(),c=j(a);o=arguments;v=this;p=a;if(c){if(void 0===l)return f=a=p,l=setTimeout(e,b),m?d(a):n;if(h)return l=setTimeout(e,b),d(p)}void 0===l&&(l=setTimeout(e,b));return n}var o,v,g,n,l,p,f=0,m=!1,h=!1,k=!0;if("function"!=typeof a)throw new TypeError(FUNC_ERROR_TEXT);b=+b||0;M(c)&&(m=!!c.leading,g=(h="maxWait"in c)?Math.max(+c.maxWait||0,b):g,k="trailing"in c?!!c.trailing:k);i.cancel=function(){void 0!==l&&clearTimeout(l);f=0;o=p=v=l=void 0};i.flush=function(){return void 0===
l?n:N(Date.now())};return i}function O(a){for(var b=0,c=0;c<a.length;c++)var d=a[c],b=b+d.price*d.quantity;return b}function w(a){localStorage.setItem("asCartContents",JSON.stringify({contents:a,timestamp:(new Date).getTime()}))}function B(){try{var a=JSON.parse(localStorage.getItem("asCartContents"));return a.timestamp<(new Date).getTime()-6048E5?(w([]),[]):a.contents||[]}catch(b){return w([]),[]}}function F(){try{return JSON.parse(localStorage.getItem("asProductViewHistory"))||[]}catch(a){return[]}}
function P(){if("function"===typeof window.asIsProductPage)try{var a=window.asIsProductPage();if(a){try{_add.push({browsed_products:[a],replace_cart_contents:!1})}catch(b){console.error(b)}var c=(new Date).getTime(),d=F().filter(function(a){return a.time>c-864E5});d.push({time:c,product:a});localStorage.setItem("asProductViewHistory",JSON.stringify(d))}}catch(j){console.log(j)}}function G(a){switch(a){case "minute":case "minutes":return 6E4;case "hour":case "hours":return 36E5;case "day":case "days":return 864E5;
default:return 1E3}}function i(a,b,c){switch(c){case "is":return a===b;case "is-not":return a!==b;case "less-than":return a<b;case "greater-than":return a>b;case "less-than-or-eq":return a<=b;case "greater-than-or-eq":return a>=b;default:return!1}}function s(a){if(null!=a.combinator)switch(a.combinator){case "all":for(var b=a.rules,c=0;c<b.length;c++)if(!s(a.rules[c]))return!1;return!0;case "any":b=a.rules;for(c=0;c<b.length;c++)if(s(a.rules[c]))return!0;return!1;case "one":for(var b=a.rules,d=0,
c=0;c<b.length;c++)s(a.rules[c])&&d++;return 1===d;case "none":b=a.rules;for(c=0;c<b.length;c++)if(s(a.rules[c]))return!1;return!0;default:return!1}switch(a.field){case "cart-value":return i(O(B()),a.value,a.operator);case "cart-count":return i(B().length,a.value,a.operator);case "logged-in":return!!C;case "device":switch(a.operator){case "is":return u===a.value;case "is-not":return u!==a.value;default:return!1}case "product-views":b=F();if("number"===typeof a.value)return i(b.length,a.value,a.operator);
for(var c=a.value.count,d=a.value.duration,j=G(a.value.unitOfTime),d=(new Date).getTime()-d*j,j=b.length-1,e=0;-1<j;)if(b[j].time>=d)e++,j--;else break;return i(e,c,a.operator);case "page-views":return"number"===typeof D?i(D,a.value,a.operator):!1;case "url-history":return b=document.URL.search(a.value.value),"is"==a.operator?"-1"!=b?!0:!1:"is-not"==a.operator?"-1"==b?!0:!1:!1;case "reward-points":return"number"===typeof x?i(x,a.value,a.operator):!1;case "percentage-scroll":return i(q,a.value,a.operator);
case "seconds-after-load":return Date.now()>=L+1E3*a.value;case "total-time-on-site":return Q.setHasRule(!0),b=y,"number"===typeof a.value?(c=a.value,d="seconds"):(c=a.value.duration,d=a.value.unitOfTime),d=G(d),i(b,c*d,a.operator);case "is-recent-session":return b=parseInt(localStorage.getItem("isErcEmail")),"number"===typeof a.value?(c=a.value,d="seconds"):(c=a.value.duration,d=a.value.unitOfTime),d=G(d),i((new Date).getTime()-c*d,b,a.operator);case "users-active-campaign":return i(t.getUsersActiveEmailCampaign(),
a.value,a.operator);case "post-purchase":var f="undefined"!==typeof AddShoppersConversion,a=Date.now(),g=36E5*(AddShoppersWidget&&AddShoppersWidget.attribution_hours?AddShoppersWidget.attribution_hours:0),d=function(a){try{return parseInt(localStorage.getItem(a),10)||0}catch(b){return 0}},o=function(){try{localStorage.setItem("asOfferCodeAttributable",JSON.stringify([{created_at:Date.now(),postPurchase:f}]))}catch(a){}},h=function(a,b,c){if(null==a)return!1;a=c-a;return 0<=a&&a<=b};if(f){b=d("isErcEmail");
if(0<b&&h(b,g,a))return o(),!0;d=d("asLastEmailAttributionCheck");0===b&&36E5<a-d&&(localStorage.setItem("asLastEmailAttributionCheck",a.toString()),b=as_resolveEnvironmentURL("https://app.shop.pe/app/triggered_email_attribution"),AddShoppersWidget.ajax({type:"POST",url:b,data:AddShoppersWidget.jsonPoly.stringify({siteId:AddShoppersWidget.id,sessionId:AddShoppersWidget.session_id,event_source:"triggered_email_click"}),contentType:"application/json; charset=UTF-8",success:function(a){var b;if((a=a&&
"object"===typeof a&&"response"in a?a.response:a)&&"object"===typeof a)b=a;else try{b=JSON.parse(a)}catch(c){b=null}if(b&&!0===b.success&&b.data&&(b=b.data,"Email Click"===b.whence))b=b.created_at,!b||"string"!==typeof b?b=null:(b=b.replace(/\.Z$/,"Z"),b=Date.parse(b),b=isNaN(b)?null:b),a=Date.now(),(null==b?0:8E3<a-b)&&h(b,g,Date.now())&&o()}}))}try{c=JSON.parse(localStorage.getItem("asOfferCodeAttributable")||"[]")}catch(k){c=[]}return 0<c.length&&(b=c[0],h(b&&b.created_at,9E5,a))?!0===b.postPurchase?
!0:f:!1;case "user-actions":switch(a.operator){case "unfocus":return r;case "return-to-home":return z;case "navigate-away":return A;case "abandon":return m;default:return!1}default:return!1}}function R(a,b){if(null!=a.combinator)for(var c=a.rules,d=0;d<c.length;d++)R(a.rules[d],b);"seconds-after-load"===a.field&&b.push(1E3*a.value)}function Y(a,b){for(var c=0;c<a.length;c++)if(b(a[c]))return a[c];return null}function S(){var a=[];h.forEach(function(b){R(b.trigger,a)});k=a.filter(function(b,c){return a.indexOf(b)===
c&&null===Y(k,function(a){return a.delay===b})}).map(function(a){var c={timeout:setTimeout(function(){var a=k.indexOf(c);0<=a&&(k.splice(a,1),e())},a),delay:a};return c}).concat(k)}function e(){for(var a=[],b=0;b<h.length;b++){var c=h[b].cb;s(h[b].trigger)?c():a.push(h[b])}h=a;setTimeout(function(){A=z=m=r=!1},300)}function T(){var a=Number(localStorage.getItem("asPageViews")),a=isNaN(Number(a))?1:Number(a)+1;localStorage.setItem("asPageViews",a)}function H(){location.pathname.slice(1)!==E&&(m=r=
!1,z="/"===location.pathname,A=!0);E=location.pathname.slice(1);g.scrollTop=g.getScrollPercent();q=g.scrollTop;T();P();F();Date.now();k.forEach(function(a){clearTimeout(a.timeout)});k=[];S();e()}function Z(a,b){for(var c=document.documentElement,d=document.body,j=b.split(","),e=0;e<j.length;e++){var f=j[e].toLowerCase();if("top"===f){var h=c&&c.scrollTop||d&&d.scrollTop||0;if(a.pageY<h)return!0}if("bottom"===f){var g=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight,
g=g+h;if(a.pageY>g)return!0}if("left"===f&&"0">=a.pageX||"right"===f&&a.pageX>=(document.documentElement.clientWidth||window.innerWidth||document.body.clientWidth))return!0}return!1}function U(a){a=a?a:window.event;Z(a,"top")&&"select"!==a.target.nodeName.toLowerCase()&&(m=!0,e(),document.removeEventListener("mouseout",U))}function t(a,b){a&&a.rules&&0<a.rules.length&&(s(a)?b():(h.push({trigger:a,cb:b}),S()))}function V(){try{var a=localStorage.getItem(I);if(null==a)return{id:null,exp:null,legacy:!1,
expired:!1};try{var b=JSON.parse(a);if(b&&"string"===typeof b.id){var c="number"===typeof b.exp?b.exp:null,d=null!=c&&(new Date).getTime()>c;return{id:b.id,exp:c,legacy:!1,expired:!!d}}}catch(e){}return{id:""+a,exp:null,legacy:!0,expired:!1}}catch(f){return{id:null,exp:null,legacy:!1,expired:!1}}}function J(a,b){try{localStorage.setItem(I,JSON.stringify({id:""+a,exp:b}))}catch(c){}}function W(){try{localStorage.removeItem(I)}catch(a){}}T();var g={settings:{},lastPos:null,newPos:null,timer:void 0,
delta:0,delay:50,didAlert:!1,scrollTop:0,clear:function(){this.lastPos=null;this.delta=0;if(!0===this.settings.resetOnClear)this.didAlert=!1},getDocHeight:function(){var a=document;try{return Math.max(a.body.scrollHeight,a.documentElement.scrollHeight,a.body.offsetHeight,a.documentElement.offsetHeight,a.body.clientHeight,a.documentElement.clientHeight)}catch(b){return Math.max(a.documentElement.scrollHeight,a.documentElement.offsetHeight,a.documentElement.clientHeight)}},getScrollPercent:function(){var a=
window.innerHeight||(document.documentElement||document.body).clientHeight,b=this.getDocHeight();return Math.floor(100*((window.pageYOffset||(document.documentElement||document.body.parentNode||document.body).scrollTop)/(b-a)))||0},checkScrollSpeed:function(){this.newPos=window.scrollY;var a=this.scrollTop;this.scrollTop=this.getScrollPercent();this.scrollTop!==a&&this.settings.scrollTask();if(null!==this.lastPos)this.delta=this.newPos-this.lastPos;this.lastPos=this.newPos;clearTimeout(this.timer);
this.timer=setTimeout(this.clear.bind(this),this.delay);if(this.delta<0-this.settings.alertThreshold&&!1===this.didAlert&&this.scrollTop>=this.settings.scrollThreshold)this.settings.alertTask(),this.didAlert=!0},init:function(a){this.settings=a||{alertThreshold:50,scrollThreshold:30,resetOnClear:!1,alertTask:function(){},scrollTask:function(){}};this.delay=this.settings.delay||50;window.addEventListener("scroll",this.checkScrollSpeed.bind(this))}},Q={_localStorageSetTimeField:"asTimeOnSiteSetTime",
_localStorageValueField:"asTimeOnSiteValue",_localStorageExpirationPeriod:432E6,_intervalTimeout:1E3,_hasRule:!1,_lastSetTime:null,_value:0,init:function(){this._hasRule=!1;this._lastSetTime=(new Date).getTime();y=this._value=this._getValueFromLocalStorage();setInterval(this._intervalHandler.bind(this),this._intervalTimeout)},setHasRule:function(a){this._hasRule=!!a},_intervalHandler:function(){var a=(new Date).getTime();this._value+=a-this._lastSetTime;this._lastSetTime=a;y=this._value;this._saveValueToLocalStorage();
this._hasRule&&e()},_getValueFromLocalStorage:function(){try{var a=(new Date).getTime(),b=localStorage.getItem(this._localStorageSetTimeField),c=null==b||isNaN(Number(b))?a:Number(b);if(a-c<this._localStorageExpirationPeriod){var d=localStorage.getItem(this._localStorageValueField);return null==d||isNaN(Number(d))?0:Number(d)}}catch(e){}return 0},_saveValueToLocalStorage:function(){try{localStorage.setItem(this._localStorageValueField,this._value),localStorage.setItem(this._localStorageSetTimeField,
this._lastSetTime)}catch(a){}}},h=[],k=[];L=Date.now();u=function(){var a=navigator.userAgent.toLowerCase();return/ipad|tablet|playbook|silk/i.test(a)||"MacIntel"===navigator.platform&&1<navigator.maxTouchPoints||window.matchMedia("(min-width: 768px) and (max-width: 1024px)").matches?"tablet":/android|iphone|ipod|blackberry|iemobile|opera mini/i.test(a)?"mobile":"pc"}();E=location.pathname.slice(1);C=null;D=Number(localStorage.getItem("asPageViews"));x=null;q=0;r=!1;z=!1;A=!1;m=!1;y=0;g.scrollTop=
g.getScrollPercent();q=g.scrollTop;var K=!1;try{K=window.top!==window.self}catch(ba){K=!0}K&&(m=!0,window.parent.postMessage({type:"minty-onsite-register-iframe",mintyIframeId:"minty-tracker-frame"},"*"));g.init({delay:5E3,alertThreshold:50,scrollThreshold:30,resetOnClear:!0,alertTask:function(){if("mobile"===u||"tablet"===u)m=!0,e()},scrollTask:function(a,b,c){var d=!0,e=!0;if("function"!=typeof a)throw new TypeError(FUNC_ERROR_TEXT);M(c)&&(d="leading"in c?!!c.leading:d,e="trailing"in c?!!c.trailing:
e);return X(a,b,{leading:d,maxWait:b,trailing:e})}(function(){q=g.scrollTop;e()},200)});if("undefined"!==typeof window.history){var f=window.history,$=f.pushState;f.pushState=function(a){if("function"==typeof f.onpushstate)f.onpushstate({state:a});var b=$.apply(f,arguments);H();return b};var aa=f.replaceState;f.replaceState=function(a){var b=aa.apply(f,arguments);H();return b};window.addEventListener("popstate",H)}window.addEventListener("blur",function(){r=!0;e()});document.addEventListener("mouseout",
U,!1);window.addEventListener("message",function(a){if(a.data&&"string"===typeof a.data.type){var b=a.data.type;if("minty-onsite-focus-lost"===b)r=!0,e();else if("minty-onsite-scroll-update"===b)q=a.data.scrollPercent,e()}});Q.init();var I="asUsersActiveEmailCampaign";t.getUsersActiveEmailCampaign=function(){var a=V();if(a.expired)return W(),null;if(a.legacy&&a.id||a.id&&null==a.exp)return J(a.id,(new Date).getTime()+6048E5),a.id;return a.id||null};t.updateUsersActiveEmailCampaign=function(a){var b=
V(),c=b.id,d=b.exp,f=!!b.expired,b=!!b.legacy;if(null==a||""===a){if(null!=c){W();try{setTimeout(e,0)}catch(g){}}}else if(a=""+a,(c!==a||b||null==d||f)&&J(a,(new Date).getTime()+6048E5),null==c&&a||c!==a||b||f)try{setTimeout(e,0)}catch(h){}};t.incrementCartCount=function(){a:{for(var a={sku:"manual",quantity:1,price:0},b=B(),c=a.sku,d=0;d<b.length;d++){var e=b[d];if(e.sku===c){e.quantity+=a.quantity;w(b);break a}}b.push(a);w(b)}};t.dataLayerLoaded=function(){try{if("function"===typeof window.asCart){var a=
function(a){return null==a||Array.isArray(a)?a:Symbol.iterator in Object(a)?Array.from(a):null},b=function(){var b;"function"===typeof window.asCartRows&&(b=a(window.asCartRows()));if("function"===typeof window.asCartItems&&(b=a(window.asCartItems(b))))w(b),_add&&_add.push&&(b=B(),_add.push({cart_contents:b,cart_value:O(b),active_cart:!0})),e()};window.asCart(b,b)}"function"===typeof window.asRewardPoints&&window.asRewardPoints(function(a){x=a;e()});"function"===typeof window.asLoggedIn&&window.asLoggedIn(function(a){C=
a;e()})}catch(c){console.log(c)}P();e()};return t}();
